<?php
/**
 * KaliCart Bridge — Uninstall
 *
 * Runs when the plugin is deleted from WP Admin → Plugins.
 * Removes all options and transients created by the plugin.
 */

defined( 'WP_UNINSTALL_PLUGIN' ) || exit;

// Capture the token before deleting its option so the generated public feed can
// be removed without scanning or recursively deleting anything in uploads.
$kalicart_bridge_acp_options = get_option( 'kalicart_bridge_acp_feed', [] );
$kalicart_bridge_acp_token   = is_array( $kalicart_bridge_acp_options )
	? (string) ( $kalicart_bridge_acp_options['token'] ?? '' )
	: '';

// Options
$kalicart_bridge_options = [
    'kalicart_bridge_badge_enabled',
    'kalicart_bridge_badge_position',
    'kalicart_bridge_robots_enabled',
    'kalicart_bridge_sitemap_enabled',
    'kalicart_bridge_checkout_enabled',
    'kalicart_bridge_well_known_enabled',
    'kalicart_bridge_agent_hints_enabled',
    'kalicart_bridge_hint_search',
    'kalicart_bridge_hint_zero',
    'kalicart_bridge_hint_category',
    'kalicart_bridge_global_consent',
    'kalicart_bridge_agent_index_url',
    'kalicart_bridge_return_policy_url',
    'kalicart_bridge_wk_version',
	'kalicart_bridge_ai_traffic_enabled',
	'kalicart_bridge_ai_traffic',
	'kalicart_bridge_agent_funnel',
	'kalicart_bridge_coupons_agent_enabled',
	'kalicart_bridge_coupons_agent_whitelist',
	'kalicart_bridge_federation_registered_at',
	'kalicart_bridge_last_external_check',
	'kalicart_bridge_acp_feed',
    'kalicart_rate_guard_checkout',
	'kalicart_rate_guard_checkout_long',
	'kalicart_rate_guard_checkout_access',
    'kalicart_rate_guard_catalog',
    'kalicart_rate_guard_mcp',
	'kalicart_rate_guard_telemetry_html',
    'kalicart_rate_guard_lock_checkout',
	'kalicart_rate_guard_lock_checkout_long',
	'kalicart_rate_guard_lock_checkout_access',
    'kalicart_rate_guard_lock_catalog',
    'kalicart_rate_guard_lock_mcp',
	'kalicart_rate_guard_lock_telemetry_html',
];
foreach ( $kalicart_bridge_options as $kalicart_bridge_option ) {
    delete_option( $kalicart_bridge_option );
}

// Cron
wp_clear_scheduled_hook( 'kalicart_bridge_facets_rebuild' );
wp_clear_scheduled_hook( 'kalicart_bridge_cleanup_claims' );
wp_clear_scheduled_hook( 'kalicart_bridge_acp_feed_generate' );

// Checkout session claim rows (kalicart_session_claimed_{id}): dynamically keyed, one per
// attributed checkout — not in the fixed options list above, needs a LIKE-pattern sweep.
global $wpdb;
$wpdb->query( $wpdb->prepare(
    "DELETE FROM {$wpdb->options} WHERE option_name LIKE %s",
    $wpdb->esc_like( 'kalicart_session_claimed_' ) . '%'
) );

// Dynamic hardening/session records cannot be enumerated in the fixed list above.
foreach ( [
	'kalicart_checkout_idem_',
	'kalicart_bridge_agent_funnel_v2_',
	'kalicart_bridge_catalog_facets_',
	'kalicart_rate_guard_lock_idem_',
	'_transient_kalicart_session_',
	'_transient_timeout_kalicart_session_',
	'_transient_kalicart_checkout_idem_',
	'_transient_timeout_kalicart_checkout_idem_',
	'_transient_kalicart_bridge_meta_',
	'_transient_timeout_kalicart_bridge_meta_',
] as $kalicart_bridge_dynamic_prefix ) {
	$wpdb->query( $wpdb->prepare(
		"DELETE FROM {$wpdb->options} WHERE option_name LIKE %s",
		$wpdb->esc_like( $kalicart_bridge_dynamic_prefix ) . '%'
	) );
}

// Transients
$kalicart_bridge_transients = [
    'kalicart_bridge_health_v2',
    'kalicart_bridge_meta',
    'kalicart_bridge_robots_checked',
	'kalicart_bridge_sitemap_written',
	'kalicart_bridge_catalog_query_cache_v1',
	'kalicart_bridge_site_ip',
	'kalicart_bridge_acp_feed_lock',
];
foreach ( $kalicart_bridge_transients as $kalicart_bridge_transient ) {
	delete_transient( $kalicart_bridge_transient );
}

// Remove only the fixed feed files inside the exact token directory generated by
// this plugin. Never recurse through uploads and never trust an arbitrary path.
if ( preg_match( '/^[A-Za-z0-9]{16,64}$/', $kalicart_bridge_acp_token ) ) {
	$kalicart_bridge_uploads = wp_upload_dir();
	$kalicart_bridge_base    = trailingslashit( $kalicart_bridge_uploads['basedir'] ) . 'kalicart-bridge/';
	$kalicart_bridge_dir     = $kalicart_bridge_base . $kalicart_bridge_acp_token . '/';
	foreach ( [ 'index.html', 'acp-products.jsonl', 'acp-products.jsonl.gz', 'acp-products.jsonl.tmp', 'acp-products.jsonl.tmp.gz' ] as $kalicart_bridge_file ) {
		$kalicart_bridge_path = $kalicart_bridge_dir . $kalicart_bridge_file;
		if ( is_file( $kalicart_bridge_path ) ) {
			wp_delete_file( $kalicart_bridge_path );
		}
	}
	if ( is_dir( $kalicart_bridge_dir ) ) {
		if ( ! function_exists( 'WP_Filesystem' ) ) {
			require_once ABSPATH . 'wp-admin/includes/file.php';
		}
		global $wp_filesystem;
		if ( WP_Filesystem() && $wp_filesystem ) {
			// Non-recursive on purpose: a merchant-owned file keeps the directory intact.
			$wp_filesystem->rmdir( $kalicart_bridge_dir, false );
		}
	}
}

// Physical discovery mirrors otherwise bypass WordPress and remain publicly
// reachable after uninstall. Delete only files whose body identifies KaliCart.
$kalicart_bridge_well_known = trailingslashit( ABSPATH ) . '.well-known/';
foreach ( [ 'agent.json', 'kalicart-bridge.json', 'agent-catalog.json', 'ucp.json', 'api-catalog.json', 'kalicart-bridge', 'agent-catalog', 'api-catalog', 'ucp' ] as $kalicart_bridge_mirror ) {
	$kalicart_bridge_path = $kalicart_bridge_well_known . $kalicart_bridge_mirror;
	if ( is_file( $kalicart_bridge_path ) ) {
		$kalicart_bridge_body = (string) @file_get_contents( $kalicart_bridge_path ); // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged -- ownership check must fail closed on unreadable files.
		if ( false !== stripos( $kalicart_bridge_body, 'kalicart' ) ) {
			wp_delete_file( $kalicart_bridge_path );
		}
	}
}
$kalicart_bridge_htaccess = $kalicart_bridge_well_known . '.htaccess';
$kalicart_bridge_legacy_htaccess = "<Files 'kalicart-bridge'>\n  ForceType application/json\n</Files>\n<Files 'agent-catalog'>\n  ForceType application/json\n</Files>\n<Files 'ucp'>\n  ForceType application/json\n</Files>\n";
if ( is_file( $kalicart_bridge_htaccess ) && (string) @file_get_contents( $kalicart_bridge_htaccess ) === $kalicart_bridge_legacy_htaccess ) { // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged -- exact ownership check.
	wp_delete_file( $kalicart_bridge_htaccess );
}
